name: CI

on:
  push:
    tags: v**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo head_ref: ${{ github.head_ref }}
          echo SHA: ${{ github.sha }}
          export
