name: CI

on:
  push:
    tags: v**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo ref_name: ${{ GITHUB.REF_NAME }}
          echo SHA: ${{ github.sha }}
